### ISSUE TITLE
doesn't implement the uploadStream function. Some performance issues may occur

### ISSUE THREAD

**Issue by qhoirulanwar** [strapi-community/strapi-provider-upload-google-cloud-storage#130] opened 2022-04-18 05:24 UTC
yarn run v1.22.15
$ strapi develop
(node:14656) Warning: The upload provider "@strapi-community/strapi-provider-upload-google-cloud-storage" doesn't implement the uploadStream function. Strapi will fallback on the upload method. Some performance issues may occur.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14656) Warning: [deprecated] In future versions, Strapi will stop reading directly from the environment variable API_TOKEN_SALT. Please set apiToken.salt in config/admin.js instead.
For security reasons, keep storing the secret in an environment variable and use env() to read it in config/admin.js (ex: `apiToken: 
{ salt: env('API_TOKEN_SALT') }`). See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.

 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Thu Apr 21 2022 14:55:30 GMT+0700 (Western Indo… │
│ Launched in        │ 32504 ms                                         │
│ Environment        │ development                                      │
│ Process PID        │ 14656                                            │
│ Version            │ 4.1.8 (node v16.13.1)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available

**Is your feature request related to a problem? Please describe.**
@strapi-community/strapi-provider-upload-google-cloud-storage@4.1.7 not 100% compatible with strapi@4.1.8

**Describe the solution you'd like**
update to latest same version with strapi

**Comment by am2222** [comment] 2022-04-23 02:14
I am also getting the same warning. Is there any quick fix for it?

**Comment by JulienHe** [comment] 2022-06-05 01:34
Any updates on this one :)?

**Comment by Lith** [comment] 2022-06-06 10:47
Hello,

Sorry for delay (again :x) 
Everyone is free to push PR :) 

I will take a look about it this week, but feel free to submit PR.
Thx

**Comment by qhoirulanwar** [comment] 2022-06-19 15:48
@Lith please check my PR https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/pull/137

**Comment by RomanLubushkin** [comment] 2022-07-04 04:30
@Lith Hey, when do you think PR might be merged?
Basically this issue is breaking plugin usage

**Comment by qnp** [comment] 2022-08-17 08:39
This issue should be closed by https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/pull/137 merged and 4.2.3 released, no ?

**Comment by mckaracan** [comment] 2023-01-05 13:20
Hello , I upgraded strapi version to 4.5.5 and this warning appears . Is there any suggestion?

**Comment by Lith** [comment] 2023-01-19 18:16
Hello ! 
Yes this issue should be close... because it's fixed since many month now :] 

@mckaracan could you please let me know if the issue is still appears for you with latest release ?
Thx.

**Closed** 2023-05-13 20:43 UTC
Labels: enhancement, fixed

**Comment by cyriaque-ovaga** [comment] 2023-06-13 23:06
steal appear for me. help please
